version: '3'

services:
  dockersyslogserver.listener:
    image: dockersyslogserver.listener
    build:
      context: ./DockerSyslogServer.Listener
      dockerfile: Dockerfile

  dockersyslogserver.api:
    image: dockersyslogserver.api
    build:
      context: ./DockerSyslogServer.API
      dockerfile: Dockerfile
